### ISSUE TITLE
"Invalid char \'\r\' at 0, 3" when deserializing glider.txt in Windows

### ISSUE THREAD

**Issue by ninjasource** [brundonsmith/life#1]
It may be a better idea to use a serialization library to read these files as different operating systems use different line endings.

Otherwise, thanks for sharing your repo!

**Comment by ninjasource** [comment]
Alternatively, here is a quick and dirty fix:
```
    pub fn from_configuration(
        data: &str,
        dead_char: char,
        alive_char: char,
    ) -> Result<Self, String> {
        let mut world = Self::new();

        let mut row = 0;
        let mut col = 0;

        for c in data.chars() {
            if c == dead_char {
                world.set(&Loc { row, col }, false);
                col += 1;
            } else if c == alive_char {
                world.set(&Loc { row, col }, true);
                col += 1;
            } else if c == '\n' {
                row += 1;
                col = 0;
            } else if c == '\r' {
                col += 1;
            } else {
                return Err(format!("Invalid char '{}' at {}, {}", c, row, col));
            }
        }

        return Ok(world);
    }
```

**Comment by brundonsmith** [comment]
Ah, yeah. Since it's a custom format a serialization library seemed like overkill, and I didn't consider this issue. If you want to make a pull request I'd be happy to make sure it still works on *nix and merge it, or I can just make the change myself later tonight.

**Comment by Arnavion** [comment]
The files are saved with Unix newlines, so they are consistent with the code that reads them. The issue is probably that OP has `git.autocrlf` set to `true` (which is also the default) which means git will locally check out those files for them with Windows newlines. They should set it to `false`.

(Setting it to `false` is a good idea in general; letting your version control software transparently change newlines is a "works on my machine" disaster waiting to happen.)

**Comment by brundonsmith** [comment]
Ah yes, I've heard about this before. It's especially annoying because most Windows software these days understands plain newlines anyway.

Still, it seems like a strict improvement for the code to handle both formats.

**Comment by ninjasource** [comment]
> 
> 
> Ah, yeah. Since it's a custom format a serialization library seemed like overkill, and I didn't consider this issue. If you want to make a pull request I'd be happy to make sure it still works on *nix and merge it, or I can just make the change myself later tonight.

You're right, it would be overkill! I don't mind, go ahead and make the change yourself, my editor changed the formatting so the pull request would have been messy anyways!

**Comment by ninjasource** [comment]
> 
> 
> The files are saved with Unix newlines, so they are consistent with the code that reads them. The issue is probably that OP has `git.autocrlf` set to `true` (which is also the default) which means git will locally check out those files for them with Windows newlines. They should set it to `false`.
> 
> (Setting it to `false` is a good idea in general; letting your version control software transparently change newlines is a "works on my machine" disaster waiting to happen.)

I didn't know that, thanks!!

**Comment by brundonsmith** [comment]
Carriage returns are handled in commit 88d651179f813f135306daf91a3bf9fd1e846d9d
