### ISSUE TITLE
Display error on Wayland

### ISSUE THREAD

**Issue by christianbundy** [brundonsmith/life#2]
Hey, cool project! When I try to run it on my machine I see this:

![Screenshot from 2020-04-08 06-55-36](https://user-images.githubusercontent.com/537700/78792453-fce8e280-7965-11ea-8231-8357b5af1763.png)

I'm running Arch Linux with Gnome Shell on Wayland, I can try out X11 and see if that helps. If you have any tips to help debug I'd love to help! :rocket:

**Comment by brundonsmith** [comment]
I'm using a fairly high-level library for creating and drawing to the window, and this bug looks pretty low-level, so what I'd do is report the issue to the underlying library ("Piston"), or possibly even a library underneath that.

Sorry it didn't work! Thanks anyway for trying it out 🙂
